### ISSUE TITLE
Multiple announcements from one service instances

### ISSUE THREAD

**Issue by joshua-rutherford** [DecipherNow/gm-fabric-jvm#69]
Today I discovered that a single instance of a Grey Matter Fabric (0.1.4) service was announcing twice in zookeeper (e.g., nodes `member_0000000120` and `member_0000000121`).  The node data for each was identical.  I confirmed that only one instance of the process was running.

I am not positive yet that this is a fabric issue and not a zookeeper issue as it occurred with two services at the same time and that is suspect.  Restarting the service cleared the double announcement.

Note that in most cases there is no functional impact to this other than the double announcing service servicing twice as many requests as other instances in a round robin load balancing mode.

**Comment by justincely** [comment]
I just encountered this too.  In a deployed environment, _all_ JVM services had this double announcement.  This did not affect any Go services. 

Abstracted logs from the services show some of the zk connection activity:
```
0:18:47.396 [ZookeeperClient-watcherProcessor-SendThread(zk_1:2181)] INFO  org.apache.zookeeper.ClientCnxn - Unable to read additional data from server sessionid 0x160e23c741fedad, likely server has closed socket, closing socket connection and attempting reconnect
00:18:47.516 [ZookeeperClient-watcherProcessor-EventThread] WARN  com.twitter.common.zookeeper.Group - Temporary error re-joining group: /services/WombatSkittles-1.0/1.2/http
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /services/WombatSkittles-1.0/1.2/http/member_
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99) ~[zookeeper-3.5.0-alpha.jar:3.5.0-alpha-1615249]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[zookeeper-3.5.0-alpha.jar:3.5.0-alpha-1615249]
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1067) ~[zookeeper-3.5.0-alpha.jar:3.5.0-alpha-1615249]
	at com.twitter.common.zookeeper.Group$ActiveMembership.join(Group.java:424) [group-0.0.91.jar:na]
	at com.twitter.common.zookeeper.Group$ActiveMembership$4.get(Group.java:445) [group-0.0.91.jar:na]
	at com.twitter.common.zookeeper.Group$ActiveMembership$4.get(Group.java:442) [group-0.0.91.jar:na]
	at com.twitter.common.util.BackoffHelper$1.get(BackoffHelper.java:109) [util-0.0.121.jar:na]
	at com.twitter.common.util.BackoffHelper$1.get(BackoffHelper.java:107) [util-0.0.121.jar:na]
	at com.twitter.common.util.BackoffHelper.doUntilResult(BackoffHelper.java:127) [util-0.0.121.jar:na]
	at com.twitter.common.util.BackoffHelper.doUntilSuccess(BackoffHelper.java:107) [util-0.0.121.jar:na]
	at com.twitter.common.zookeeper.Group$ActiveMembership.tryJoin(Group.java:467) [group-0.0.91.jar:na]
	at com.twitter.common.zookeeper.Group$ActiveMembership.access$800(Group.java:316) [group-0.0.91.jar:na]
	at com.twitter.common.zookeeper.Group$ActiveMembership$3.process(Group.java:433) [group-0.0.91.jar:na]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:539) [zookeeper-3.5.0-alpha.jar:3.5.0-alpha-1615249]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:515) [zookeeper-3.5.0-alpha.jar:3.5.0-alpha-1615249]
00:18:49.489 [ZookeeperClient-watcherProcessor-SendThread(zk_1:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server zk_1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
00:18:49.489 [ZookeeperClient-watcherProcessor-SendThread(zk_1:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established to zk_1/127.0.0.1:2181, initiating session
00:18:49.490 [ZookeeperClient-watcherProcessor-SendThread(zk_1:2181)] WARN  o.apache.zookeeper.ClientCnxnSocket - Connected to an old server; r-o mode will be unavailable
00:18:49.490 [ZookeeperClient-watcherProcessor-SendThread(zk_1:2181)] INFO  org.apache.zookeeper.ClientCnxn - Unable to reconnect to ZooKeeper service, session 0x160e23c741fedad has expired, closing socket connection
00:18:49.591 [ZookeeperClient-watcherProcessor-EventThread] WARN  com.twitter.common.zookeeper.Group - Temporary error re-joining group: /services/WombatSkittles-1.0/1.2/http
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /services/WombatSkittles-1.0/1.2/http/member_
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:131) ~[zookeeper-3.5.0-alpha.jar:3.5.0-alpha-1615249]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[zookeeper-3.5.0-alpha.jar:3.5.0-alpha-1615249]
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1067) ~[zookeeper-3.5.0-alpha.jar:3.5.0-alpha-1615249]
	at com.twitter.common.zookeeper.Group$ActiveMembership.join(Group.java:424) [group-0.0.91.jar:na]
	at com.twitter.common.zookeeper.Group$ActiveMembership$4.get(Group.java:445) [group-0.0.91.jar:na]
	at com.twitter.common.zookeeper.Group$ActiveMembership$4.get(Group.java:442) [group-0.0.91.jar:na]
	at com.twitter.common.util.BackoffHelper$1.get(BackoffHelper.java:109) [util-0.0.121.jar:na]
	at com.twitter.common.util.BackoffHelper$1.get(BackoffHelper.java:107) [util-0.0.121.jar:na]
	at com.twitter.common.util.BackoffHelper.retryWork(BackoffHelper.java:139) [util-0.0.121.jar:na]
	at com.twitter.common.util.BackoffHelper.doUntilResult(BackoffHelper.java:128) [util-0.0.121.jar:na]
	at com.twitter.common.util.BackoffHelper.doUntilSuccess(BackoffHelper.java:107) [util-0.0.121.jar:na]
	at com.twitter.common.zookeeper.Group$ActiveMembership.tryJoin(Group.java:467) [group-0.0.91.jar:na]
	at com.twitter.common.zookeeper.Group$ActiveMembership.access$800(Group.java:316) [group-0.0.91.jar:na]
	at com.twitter.common.zookeeper.Group$ActiveMembership$3.process(Group.java:433) [group-0.0.91.jar:na]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:539) [zookeeper-3.5.0-alpha.jar:3.5.0-alpha-1615249]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:515) [zookeeper-3.5.0-alpha.jar:3.5.0-alpha-1615249]
00:18:51.591 [ZookeeperClient-watcherProcessor-EventThread] INFO  org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=zk_1:2181 sessionTimeout=4000 watcher=com.twitter.common.zookeeper.ZooKeeperClient$3@317fd255
00:18:51.595 [ZookeeperClient-watcherProcessor-SendThread(zk_1:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server zk_1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
00:18:51.596 [ZookeeperClient-watcherProcessor-SendThread(zk_1:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established to zk_1/127.0.0.1:2181, initiating session
00:18:51.602 [ZookeeperClient-watcherProcessor-SendThread(zk_1:2181)] WARN  o.apache.zookeeper.ClientCnxnSocket - Connected to an old server; r-o mode will be unavailable
00:18:51.602 [ZookeeperClient-watcherProcessor-SendThread(zk_1:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server zk_1/127.0.0.1:2181, sessionid = 0x160e23c74203334, negotiated timeout = 4000
00:18:51.605 [ZookeeperClient-watcherProcessor-EventThread] INFO  com.twitter.common.zookeeper.Group - Set group member ID to member_0000000146
00:18:51.636 [ZookeeperClient-watcherProcessor-EventThread] INFO  com.twitter.common.zookeeper.Group - Set group member ID to member_0000000146
00:18:51.638 [ZookeeperClient-watcherProcessor-EventThread] INFO  com.twitter.common.zookeeper.Group - Set group member ID to member_0000000146
00:18:51.646 [ZookeeperClient-watcherProcessor-EventThread] INFO  com.twitter.common.zookeeper.Group - Set group member ID to member_0000000146
00:18:51.647 [ZookeeperClient-watcherProcessor-EventThread] INFO  c.t.c.zookeeper.ZooKeeperClient - Zookeeper session expired. Event: WatchedEvent state:Expired type:None path:null
00:18:51.649 [ZookeeperClient-watcherProcessor-EventThread] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x160e23c74203334 closed
00:18:51.649 [ZookeeperClient-watcherProcessor-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down
00:18:51.650 [ZookeeperClient-watcherProcessor] INFO  org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=zk_1:2181 sessionTimeout=4000 watcher=com.twitter.common.zookeeper.ZooKeeperClient$3@67e5afeb
00:18:51.651 [ZookeeperClient-watcherProcessor-SendThread(zk_1:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server zk_1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
00:18:51.651 [ZookeeperClient-watcherProcessor-SendThread(zk_1:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established to zk_1/127.0.0.1:2181, initiating session
00:18:51.654 [ZookeeperClient-watcherProcessor-SendThread(zk_1:2181)] WARN  o.apache.zookeeper.ClientCnxnSocket - Connected to an old server; r-o mode will be unavailable
00:18:51.654 [ZookeeperClient-watcherProcessor-SendThread(zk_1:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server zk_1/127.0.0.1:2181, sessionid = 0x160e23c74203336, negotiated timeout = 4000
00:18:51.657 [ZookeeperClient-watcherProcessor] INFO  com.twitter.common.zookeeper.Group - Set group member ID to member_0000000148
00:18:51.657 [ZookeeperClient-watcherProcessor-EventThread] INFO  com.twitter.common.zookeeper.Group - Set group member ID to member_0000000148
00:18:51.661 [ZookeeperClient-watcherProcessor] INFO  com.twitter.common.zookeeper.Group - Set group member ID to member_0000000149
00:18:51.661 [ZookeeperClient-watcherProcessor-EventThread] INFO  com.twitter.common.zookeeper.Group - Set group member ID to member_0000000149
00:18:51.672 [ZookeeperClient-watcherProcessor-EventThread] INFO  com.twitter.common.zookeeper.Group - Set group member ID to member_0000000148
00:18:51.672 [ZookeeperClient-watcherProcessor] INFO  com.twitter.common.zookeeper.Group - Set group member ID to member_0000000148
00:18:51.679 [ZookeeperClient-watcherProcessor-EventThread] INFO  com.twitter.common.zookeeper.Group - Set group member ID to member_0000000149
00:18:51.679 [ZookeeperClient-watcherProcessor] INFO  com.twitter.common.zookeeper.Group - Set group member ID to member_0000000149
00:18:51.682 [ZookeeperClient-watcherProcessor-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down
```

**Comment by joshua-rutherford** [comment]
@justincely, with that change we made to your discovery service this would actually appear differently in your version if deployed.  Basically, the discovery service should assume those two instances are the same as it no longer cares at all about the zk pathing, only about the service, version, ip and port.  Those are all the same so I'd expect this behavior not to impact you at all.

**Comment by justincely** [comment]
this was before I moved to the custom discovery service

**Comment by joshua-rutherford** [comment]
but it persisted after, right?
